services:
  notes_nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php_code/public:/var/www/html/public:ro
    depends_on:
      - notes_php
      - notes_db

  notes_php:
    build: ./php_code/
    volumes:
      - ./php_code/:/var/www/html/

  notes_db:
    image: mariadb
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: notes
    secrets:
      - mysql_root_password

secrets:
  mysql_root_password:
    file: secrets/mysql_root_password.txt